### ISSUE TITLE
vueCompilerOptions is not working

### ISSUE THREAD

**Issue by huang-julien** [huang-julien/nuxt-runtime-compiler#36]
Thanks @huang-julien! The [nuxt-runtime-compiler](https://www.npmjs.com/package/nuxt-runtime-compiler) works well for us!

One thing...
We are using the `vue.compilerOptions.isCustomElement` option in the `nuxt.config.ts` as mentioned here: https://github.com/vuejs/core/issues/3746#issuecomment-835766808

(Because we are using [Katex](https://github.com/KaTeX/KaTeX))

Could it be that this configuration does not reach the runtime compiler?

_Originally posted by @abdonrd in https://github.com/nuxt/framework/issues/4762#issuecomment-1406632473_

**Comment by huang-julien** [comment]
Hi @abdonrd👋 ,
This option should be working (at least for me). Do you have a small reproduction or show me the content of your `nuxt.config.ts` ?

**Comment by abdonrd** [comment]
Hi!

Here you have an small repo:
https://github.com/abdonrd/nuxt-runtime-compiler-demo

<img width="1371" alt="Screenshot 2023-01-29 at 10 36 54 PM" src="https://user-images.githubusercontent.com/1007051/215382329-2a6aecac-b77e-49b3-99cb-cd26db8ace19.png">

**Comment by abdonrd** [comment]
BTW, I need to downgrade Nuxt to v3.0.0, if not I can add `nuxt-runtime-compiler`.

**Comment by huang-julien** [comment]
I could reproduce the issue thank you ! 
I just debugged this and it seems that the compiler options are lost in the component instance server side 🤔 

The only workaround for now is to add the compiler option in your component definition:
````ts
`const root = defineComponent({
  template: katex.renderToString(props.content),
  compilerOptions: {
    isCustomElement: (tag: string) => [
      'math',
      'maction',
      'maligngroup',
      'malignmark',
      'menclose',
      'merror',
      'mfenced',
      'mfrac',
      'mi',
      'mlongdiv',
      'mmultiscripts',
      'mn',
      'mo',
      'mover',
      'mpadded',
      'mphantom',
      'mroot',
      'mrow',
      'ms',
      'mscarries',
      'mscarry',
      'mscarries',
      'msgroup',
      'mstack',
      'mlongdiv',
      'msline',
      'mstack',
      'mspace',
      'msqrt',
      'msrow',
      'mstack',
      'mstack',
      'mstyle',
      'msub',
      'msup',
      'msubsup',
      'mtable',
      'mtd',
      'mtext',
      'mtr',
      'munder',
      'munderover',
      'semantics',
      'math',
      'mi',
      'mn',
      'mo',
      'ms',
      'mspace',
      'mtext',
      'menclose',
      'merror',
      'mfenced',
      'mfrac',
      'mpadded',
      'mphantom',
      'mroot',
      'mrow',
      'msqrt',
      'mstyle',
      'mmultiscripts',
      'mover',
      'mprescripts',
      'msub',
      'msubsup',
      'msup',
      'munder',
      'munderover',
      'none',
      'maligngroup',
      'malignmark',
      'mtable',
      'mtd',
      'mtr',
      'mlongdiv',
      'mscarries',
      'mscarry',
      'msgroup',
      'msline',
      'msrow',
      'mstack',
      'maction',
      'semantics',
      'annotation',
      'annotation-xml'
    ].includes(tag)
  }
})
````

**Comment by huang-julien** [comment]
I'll check tomorrow how this can be fixed

**Comment by huang-julien** [comment]
Within the [docs](https://nuxt.com/docs/api/configuration/nuxt-config/#compileroptions-1), it seems that the vue compiler options are passed only at build time 🤔

**Comment by abdonrd** [comment]
Sounds good, thanks @huang-julien!
