### ISSUE TITLE
Can I compile a single vue file?

### ISSUE THREAD

**Issue by just-test-code** [huang-julien/nuxt-runtime-compiler#49]
Example: https://github.com/FranckFreiburger/vue3-sfc-loader

But it is working on the browser side to compile vue,
 I think nuxt is rendering on the server side, maybe can ignore this step and build vue file on the server side

**Comment by huang-julien** [comment]
Hi :wave: this module brings the runtime bundle of vue which includes the template compiler. This does not include the sfc compiler.
BTW if you're using this module, this module has been merged into nuxt core as a direct feature.
